/**
 * Centralized audit action constants.
 *
 * Every auditable event in the system MUST use one of these constants.
 * Grouped by domain for readability and easy extension.
 */
export const AUDIT_ACTIONS = {
  // ── Authentication ──────────────────────────────────────────────────────
  AUTH: {
    USER_REGISTERED: 'USER_REGISTERED',
    EMAIL_VERIFIED: 'EMAIL_VERIFIED',
    VERIFICATION_EMAIL_RESENT: 'VERIFICATION_EMAIL_RESENT',
    MOBILE_OTP_SENT: 'MOBILE_OTP_SENT',
    MOBILE_OTP_VERIFIED: 'MOBILE_OTP_VERIFIED',
    PROFILE_COMPLETED: 'PROFILE_COMPLETED',
    USER_LOGIN: 'USER_LOGIN',
    USER_LOGIN_FAILED: 'USER_LOGIN_FAILED',
    TWO_FACTOR_VERIFIED: 'TWO_FACTOR_VERIFIED',
    TWO_FACTOR_FAILED: 'TWO_FACTOR_FAILED',
    USER_LOGOUT: 'USER_LOGOUT',
    USER_LOGOUT_ALL: 'USER_LOGOUT_ALL',
    TOKEN_REFRESHED: 'TOKEN_REFRESHED',
    DEVICE_REVOKED: 'DEVICE_REVOKED',
    EMAIL_CHANGE_REQUESTED: 'EMAIL_CHANGE_REQUESTED',
    EMAIL_CHANGE_FAILED: 'EMAIL_CHANGE_FAILED',
    PRIMARY_EMAIL_CHANGED: 'PRIMARY_EMAIL_CHANGED',
    PRIMARY_EMAIL_REVERTED: 'PRIMARY_EMAIL_REVERTED',
  },

  // ── User Management ─────────────────────────────────────────────────────
  USER: {
    UPDATED: 'USER_UPDATED',
    DELETED: 'USER_DELETED',
    PASSWORD_RESET: 'USER_PASSWORD_RESET',
    VERIFICATION_LINK_SENT: 'USER_VERIFICATION_LINK_SENT',
    EMAIL_LINK_VERIFIED: 'USER_EMAIL_LINK_VERIFIED',
    FORGOT_PASSWORD_EMAIL_SENT: 'USER_FORGOT_PASSWORD_EMAIL_SENT',
    FORGOT_PASSWORD_RESET: 'USER_FORGOT_PASSWORD_RESET',
    TWO_FACTOR_QR_GENERATED: 'USER_2FA_QR_GENERATED',
    TWO_FACTOR_ENABLED: 'USER_2FA_ENABLED',
    TWO_FACTOR_DISABLED: 'USER_2FA_DISABLED',
  },

  // ── Campaigns ───────────────────────────────────────────────────────────
  CAMPAIGN: {
    CREATED: 'CAMPAIGN_CREATED',
    UPDATED: 'CAMPAIGN_UPDATED',
    DELETED: 'CAMPAIGN_DELETED',
    SENT: 'CAMPAIGN_SENT',
    PAUSED: 'CAMPAIGN_PAUSED',
    RESUMED: 'CAMPAIGN_RESUMED',
    AUDIENCE_CREATED: 'CAMPAIGN_AUDIENCE_CREATED',
    AUDIENCE_UPDATED: 'CAMPAIGN_AUDIENCE_UPDATED',
    AUDIENCE_DELETED: 'CAMPAIGN_AUDIENCE_DELETED',
    RECIPIENT_UNSUBSCRIBED: 'CAMPAIGN_RECIPIENT_UNSUBSCRIBED',
    RECIPIENT_RESUBSCRIBED: 'CAMPAIGN_RECIPIENT_RESUBSCRIBED',
    RECIPIENT_TRACKING_OPTOUT: 'CAMPAIGN_RECIPIENT_TRACKING_OPTOUT',
    SUPPRESSION_ADDED: 'CAMPAIGN_SUPPRESSION_ADDED',
    SUPPRESSION_REMOVED: 'CAMPAIGN_SUPPRESSION_REMOVED',
  },

  // ── Templates ───────────────────────────────────────────────────────────
  TEMPLATE: {
    CREATED: 'TEMPLATE_CREATED',
    UPDATED: 'TEMPLATE_UPDATED',
    DELETED: 'TEMPLATE_DELETED',
    PUBLISHED: 'TEMPLATE_PUBLISHED',
    CLONED: 'TEMPLATE_CLONED',
    LISTED_MARKETPLACE: 'TEMPLATE_LISTED_MARKETPLACE',
    UNLISTED_MARKETPLACE: 'TEMPLATE_UNLISTED_MARKETPLACE',
    MODERATION_FLAGGED: 'TEMPLATE_MODERATION_FLAGGED',
    MODERATION_APPROVED: 'TEMPLATE_MODERATION_APPROVED',
    MODERATION_REJECTED: 'TEMPLATE_MODERATION_REJECTED',
  },

  // ── Email Addresses ─────────────────────────────────────────────────────
  EMAIL_ADDRESS: {
    ADDED: 'EMAIL_ADDRESS_ADDED',
    OTP_SENT: 'EMAIL_ADDRESS_OTP_SENT',
    VERIFIED: 'EMAIL_ADDRESS_VERIFIED',
    REMOVED: 'EMAIL_ADDRESS_REMOVED',
    WHITELIST_SYNCED: 'EMAIL_WHITELIST_SYNCED',
  },

  // ── SMTP / Mail Sending ─────────────────────────────────────────────────
  MAIL: {
    SENT_VIA_TEMPLATE: 'MAIL_SENT_VIA_TEMPLATE',
    TEST_EMAIL_SENT: 'MAIL_TEST_EMAIL_SENT',
    API_EMAIL_SENT: 'MAIL_API_EMAIL_SENT',
    SMTP_EMAIL_SENT: 'MAIL_SMTP_EMAIL_SENT',
    EMAIL_BLOCKED: 'MAIL_EMAIL_BLOCKED',
    EMAIL_QUARANTINED: 'MAIL_EMAIL_QUARANTINED',
  },

  API_KEY: {
    CREATED: 'API_KEY_CREATED',
    REVOKED: 'API_KEY_REVOKED',
  },

  SMTP_CREDENTIAL: {
    CREATED: 'SMTP_CREDENTIAL_CREATED',
    ROTATED: 'SMTP_CREDENTIAL_ROTATED',
    REVOKED: 'SMTP_CREDENTIAL_REVOKED',
  },

  // ── CRM: Contacts ──────────────────────────────────────────────────────
  CONTACT: {
    CREATED: 'CONTACT_CREATED',
    UPDATED: 'CONTACT_UPDATED',
    DELETED: 'CONTACTS_DELETED',
  },

  // ── CRM: Companies ─────────────────────────────────────────────────────
  COMPANY: {
    CREATED: 'COMPANY_CREATED',
    UPDATED: 'COMPANY_UPDATED',
    DELETED: 'COMPANIES_DELETED',
    CONTACTS_ADDED: 'COMPANY_CONTACTS_ADDED',
    CONTACTS_REMOVED: 'COMPANY_CONTACTS_REMOVED',
  },

  // ── CRM: Lists ──────────────────────────────────────────────────────────
  LIST: {
    CREATED: 'LIST_CREATED',
    UPDATED: 'LIST_UPDATED',
    DELETED: 'LISTS_DELETED',
    CONTACTS_ADDED: 'LIST_CONTACTS_ADDED',
    CONTACTS_REMOVED: 'LIST_CONTACTS_REMOVED',
    FOLDER_CREATED: 'LIST_FOLDER_CREATED',
    FOLDER_UPDATED: 'LIST_FOLDER_UPDATED',
    FOLDER_DELETED: 'LIST_FOLDER_DELETED',
  },

  // ── Forms ───────────────────────────────────────────────────────────────
  FORM: {
    CONTACT_US_SUBMITTED: 'FORM_CONTACT_US_SUBMITTED',
    GRIEVANCE_SUBMITTED: 'FORM_GRIEVANCE_SUBMITTED',
    NEWSLETTER_SUBSCRIBED: 'FORM_NEWSLETTER_SUBSCRIBED',
    CAREER_SUBMITTED: 'FORM_CAREER_SUBMITTED',
    CONTACT_US_UPDATED: 'FORM_CONTACT_US_UPDATED',
    GRIEVANCE_UPDATED: 'FORM_GRIEVANCE_UPDATED',
    CAREER_UPDATED: 'FORM_CAREER_UPDATED',
    NEWSLETTER_UNSUBSCRIBED: 'FORM_NEWSLETTER_UNSUBSCRIBED',
  },

  // ── Domains ─────────────────────────────────────────────────────────────
  DOMAIN: {
    ADDED: 'DOMAIN_ADDED',
    DNS_VERIFIED: 'DOMAIN_DNS_VERIFIED',
    REMOVED: 'DOMAIN_REMOVED',
  },

  // ── Settings / 2FA ──────────────────────────────────────────────────────
  SETTINGS: {
    AUTHENTICATOR_SETUP: '2FA_AUTHENTICATOR_SETUP',
    AUTHENTICATOR_ENABLED: '2FA_AUTHENTICATOR_ENABLED',
    PASSKEY_REGISTERED: '2FA_PASSKEY_REGISTERED',
    PASSKEY_RENAMED: '2FA_PASSKEY_RENAMED',
    PASSKEY_REMOVED: '2FA_PASSKEY_REMOVED',
    AUTHENTICATOR_DISABLED: '2FA_AUTHENTICATOR_DISABLED',
    BACKUP_CODES_REGENERATED: '2FA_BACKUP_CODES_REGENERATED',
    EMAIL_OTP_SENT: '2FA_EMAIL_OTP_SENT',
    EMAIL_ENABLED: '2FA_EMAIL_ENABLED',
    EMAIL_DISABLE_OTP_SENT: '2FA_EMAIL_DISABLE_OTP_SENT',
    EMAIL_DISABLED: '2FA_EMAIL_DISABLED',
    PHONE_OTP_SENT: '2FA_PHONE_OTP_SENT',
    PHONE_ENABLED: '2FA_PHONE_ENABLED',
    PHONE_DISABLE_OTP_SENT: '2FA_PHONE_DISABLE_OTP_SENT',
    PHONE_DISABLED: '2FA_PHONE_DISABLED',
  },

  // ── Notifications ───────────────────────────────────────────────────────
  NOTIFICATION: {
    PREFERENCES_UPDATED: 'NOTIFICATION_PREFERENCES_UPDATED',
  },

  // ── Email Events (system-level) ─────────────────────────────────────────
  EMAIL_EVENT: {
    SENT: 'EMAIL_SENT',
    DELIVERED: 'EMAIL_DELIVERED',
    BOUNCED: 'EMAIL_BOUNCED',
    OPENED: 'EMAIL_OPENED',
    CLICKED: 'EMAIL_CLICKED',
    SPAM_COMPLAINT: 'SPAM_COMPLAINT',
    UNSUBSCRIBE: 'EMAIL_UNSUBSCRIBE',
  },

  // ── Security ────────────────────────────────────────────────────────────
  SECURITY: {
    RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
    IP_BLOCKED: 'IP_BLOCKED',
    UNAUTHORIZED_ACCESS: 'UNAUTHORIZED_ACCESS',
  },

  // ── Changelog ───────────────────────────────────────────────────────────
  CHANGELOG: {
    CREATED: 'CHANGELOG_CREATED',
    UPDATED: 'CHANGELOG_UPDATED',
    DELETED: 'CHANGELOG_DELETED',
  },
  /**
   * Organization authorization changes. Role and ownership mutations were
   * entirely unaudited before the RBAC refactor — these are the highest-value
   * events in the catalogue, since they change who can do what.
   */
  AUTHORIZATION: {
    ROLE_CREATED: 'ORG_ROLE_CREATED',
    ROLE_UPDATED: 'ORG_ROLE_UPDATED',
    ROLE_DELETED: 'ORG_ROLE_DELETED',
    ROLE_CLONED: 'ORG_ROLE_CLONED',
    ROLE_PERMISSIONS_CHANGED: 'ORG_ROLE_PERMISSIONS_CHANGED',
    MEMBER_ROLE_ASSIGNED: 'ORG_MEMBER_ROLE_ASSIGNED',
    MEMBER_ROLE_REMOVED: 'ORG_MEMBER_ROLE_REMOVED',
    OWNER_ADDED: 'ORG_OWNER_ADDED',
    OWNER_REMOVED: 'ORG_OWNER_REMOVED',
    OWNERSHIP_TRANSFERRED: 'ORG_OWNERSHIP_TRANSFERRED',
    PERMISSION_DENIED: 'AUTHORIZATION_PERMISSION_DENIED',
    MAILBOX_ACCESS_CHANGED: 'ORG_MEMBER_MAILBOX_ACCESS_CHANGED',
  },
  BILLING: {
    CUSTOMER_CREATED: 'BILLING_CUSTOMER_CREATED',
    SUBSCRIPTION_CREATED: 'BILLING_SUBSCRIPTION_CREATED',
    SUBSCRIPTION_UPDATED: 'BILLING_SUBSCRIPTION_UPDATED',
    SUBSCRIPTION_CANCELLED: 'BILLING_SUBSCRIPTION_CANCELLED',
    INVOICE_GENERATED: 'BILLING_INVOICE_GENERATED',
  },
} as const;

/**
 * Resource types for audit log entries.
 */
export const AUDIT_RESOURCE = {
  USER: 'User',
  EMAIL: 'Email',
  CAMPAIGN: 'Campaign',
  TEMPLATE: 'Template',
  CONTACT: 'Contact',
  COMPANY: 'Company',
  LIST: 'List',
  FOLDER: 'Folder',
  DOMAIN: 'Domain',
  DEVICE: 'Device',
  FORM: 'Form',
  NOTIFICATION: 'Notification',
  EMAIL_ADDRESS: 'EmailAddress',
  API_KEY: 'ApiKey',
  SMTP_CREDENTIAL: 'SmtpCredential',
  SETTINGS: 'Settings',
  CONFIG: 'Config',
  MARKETPLACE: 'Marketplace',
  CHANGELOG: 'Changelog',
  RATE_LIMIT: 'RateLimit',
  BILLING: 'Billing',
  ORGANIZATION: 'Organization',
  ORGANIZATION_ROLE: 'OrganizationRole',
  ORGANIZATION_MEMBER: 'OrganizationMember',
} as const;

/**
 * Audit severity levels.
 */
export const AUDIT_SEVERITY = {
  INFO: 'INFO',
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  CRITICAL: 'CRITICAL',
} as const;

/**
 * Audit status values.
 */
export const AUDIT_STATUS = {
  SUCCESS: 'SUCCESS',
  FAILURE: 'FAILURE',
  PENDING: 'PENDING',
  ALERT: 'ALERT',
} as const;

/**
 * Audit category values.
 */
export const AUDIT_CATEGORY = {
  AUTHENTICATION: 'authentication',
  SECURITY: 'security',
  EMAIL: 'email',
  CAMPAIGN: 'campaign',
  TEMPLATE: 'template',
  USER_MANAGEMENT: 'user-management',
  CRM: 'crm',
  FORMS: 'forms',
  CONFIGURATION: 'configuration',
  COMPLIANCE: 'compliance',
  MARKETPLACE: 'marketplace',
  NOTIFICATION: 'notification',
  CHANGELOG: 'changelog',
  BILLING: 'billing',
} as const;
