export const MINIO_CONSTANTS = {
  MINIO_ACCESS_KEY: 'MINIO_ACCESS_KEY',
  MINIO_SECRET_KEY: 'MINIO_SECRET_KEY',
  MINIO_ENDPOINT: 'MINIO_ENDPOINT',
  MINIO_EXTERNAL_HOST: 'MINIO_EXTERNAL_HOST',
  MINIO_PORT: 'MINIO_PORT',
  MINIO_USE_SSL: 'MINIO_USE_SSL',
};
